---
version: "3.8"

services:

  livy:
    image: livy-base:0.7.1
    # build:
    #   context: .
    #   dockerfile: base.Dockerfile
    container_name: livy
    hostname: livy
    command: livy
    ports:
      - target: 8998
        published: 8998
        mode: host
    volumes:
      - type: volume
        source: livy-volume
        target: /tmp/logs/livy
    networks:
      - main-network
    env_file:
      - ./spark.env
      - ./hadoop.env
      - ./livy.env
    restart: always


networks:
  main-network:
    name: main-network
    external: false
    driver: bridge
    attachable: false


volumes:
  livy-volume:
