---
version: "3.8"

services:

  livy:
    image: livy-base:0.7.1
    # build:
    #   context: .
    #   dockerfile: base.Dockerfile
    container_name: livy
    hostname: livy
    command: livy
    ports:
      - target: 8998
        published: 8998
        mode: host
    volumes:
      - type: bind
        source: ${APPS_LOGS}/livy
        target: /tmp/logs/livy
    networks:
      - main-overlay-network
    env_file:
      - ${APPS_ENV}/spark.env
      - ${APPS_ENV}/hadoop.env
      - ${APPS_ENV}/livy.env
    restart: always


networks:
  main-overlay-network:
    external: true
    driver: overlay
    attachable: true
